apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
  namespace: nettest
data:
  SERVICE_NAME: "app1-loadgen"
  TARGET_URL: "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api/app2"
  LOAD_RPS: "2"
  THREAD_POOL_SIZE: "500"
  KEEP_ALIVE: "true"
  ENABLE_LOAD_GENERATION: "true"
  CONNECTION_TIMEOUT_MS: "5000"
  READ_TIMEOUT_MS: "30000"
