apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
  namespace: nettest
data:
  SERVICE_NAME: "app1-loadgen"
  TARGET_URL: "http://app2-service:8080"
  LOAD_RPS: "5000"
  THREAD_POOL_SIZE: "500"
  KEEP_ALIVE: "true"
