# app2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: nettest
spec:
  type: ClusterIP 
  selector:
    app: app2 # Matches the app2 Deployment labels
  ports:
  - port: 8080        # Service port (used by Ingress Backend)
    targetPort: 8080  # Container port