apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2-internal
  namespace: nettest
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
spec:
  rules:
  - host: app2.internal.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app2-service
            port:
              number: 8080

