# app2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: nettest
spec:
  # The HTTPRoute can use ClusterIP Services with or without a headless (clusterIP: None) setting.
  # For RILB, the selector is key to finding the pods.
  type: ClusterIP 
  selector:
    app: app2 # MUST match the label on your app2 deployment (app: app2)
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP

