apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2-internal-ingress
  namespace: nettest
  annotations:
    # rate limitin
    nginx.ingress.kubernetes.io/limit-rps: "100"
    kubernetes.io/ingress.class: nginx 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    
spec:
  rules:
  - http:
      paths:
      - path: /api/app2(/|$)(.*) 
        pathType: ImplementationSpecific
        backend:
          service:
            name: app2-service 
            port:
              number: 8080
    