apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app2-internal-route
  namespace: nettest
spec:
  hostnames:
  - app2.internal
  parentRefs:
  - name: omni-gateway
    namespace: omni-system
  rules:
  - backendRefs:
    - name: app2-service
      port: 8080
