# app2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: nettest
spec:
  type: ClusterIP 
  selector:
    app: app2 # Matches the app2 Deployment labels
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP

