apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app2-route
  namespace: nettest
spec:
  parentRefs:
  - name: internal-gw

  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/app2
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: "/"
    backendRefs:
    - name: app2-service
      port: 8080
